// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClQ7641_KcaXNUiZysNKv6g08-_2hGGnE',
    appId: '1:567288230556:web:2d95f1244be18c9bd43359',
    messagingSenderId: '567288230556',
    projectId: 'addrive-5f8ea',
    authDomain: 'addrive-5f8ea.firebaseapp.com',
    storageBucket: 'addrive-5f8ea.firebasestorage.app',
    measurementId: 'G-Q97DMP62JS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrkVLXeuUcqbDl-qEC88kh-xr9M8JdWwI',
    appId: '1:567288230556:android:84b90660938411a8d43359',
    messagingSenderId: '567288230556',
    projectId: 'addrive-5f8ea',
    storageBucket: 'addrive-5f8ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAel8CLVWTr9WhOTX7ba84rdbkGPZzPw6s',
    appId: '1:567288230556:ios:b244948dd3675399d43359',
    messagingSenderId: '567288230556',
    projectId: 'addrive-5f8ea',
    storageBucket: 'addrive-5f8ea.firebasestorage.app',
    iosBundleId: 'com.techfifo.addrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAel8CLVWTr9WhOTX7ba84rdbkGPZzPw6s',
    appId: '1:567288230556:ios:b244948dd3675399d43359',
    messagingSenderId: '567288230556',
    projectId: 'addrive-5f8ea',
    storageBucket: 'addrive-5f8ea.firebasestorage.app',
    iosBundleId: 'com.techfifo.addrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClQ7641_KcaXNUiZysNKv6g08-_2hGGnE',
    appId: '1:567288230556:web:d3a147cf029f8479d43359',
    messagingSenderId: '567288230556',
    projectId: 'addrive-5f8ea',
    authDomain: 'addrive-5f8ea.firebaseapp.com',
    storageBucket: 'addrive-5f8ea.firebasestorage.app',
    measurementId: 'G-N8Z2QDZMJX',
  );
}
